server:
  port: 8082

spring:
  application:
    name: authentication
  datasource:
    url: jdbc:mysql://localhost:3306/payflow
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: create

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka