server:
  port: 8081

spring:
  application:
    name: user
  datasource:
    url: jdbc:mysql://localhost:3306/payflow
    username: root
    password: root

  jpa:
    hibernate:
      show_sql: true
      format_sql: true
      ddl-auto: update

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka