version: '3.3'

services:
  postgres_db:
    container_name: mysql
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: payflow
      MYSQL_PASSWORD: payflow-pass
    ports:
      - "3306:3306"
    networks:
      - payflow
    volumes:
      - mysql_data:/var/lib/mysql

networks:
  payflow:
    driver: bridge

volumes:
  mysql_data: